import Link from "next/link";
import type { Metadata } from "next";
import { AuthProvider } from "@/context/auth";
import AuthButtons from "@/components/auth-buttons";
import { HomeIcon } from "lucide-react";
import { Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <AuthProvider>
          <nav className="flex items-center justify-between bg-sky-950 text-white p-2 md:p-5 h-16 md:h-24 ">
            <Link
              href="/"
              className="flex items-center gap-2 text-3xl tracking-wide uppercase"
            >
              <HomeIcon className="hidden sm:block" />
              <span className="text-xl sm:text-2xl md:text-3xl">Fire Homes</span>
            </Link>
            <ul className="flex items-center space-x-6">
              <li>
                <Link
                  href="/property-search"
                  className="text-[13px] sm:text-lg uppercase tracking-wide hover:underline"
                >
                  Property search
                </Link>
              </li>
              <li>
                <AuthButtons />
              </li>
            </ul>
          </nav>
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
